//
// ArtworksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ArtworksAPI {

    /**
     Artworks List
     
     - parameter page: (query) Number of page 
     - parameter itemsPerPage: (query) Limit of artworks by page 
     - parameter hasImages: (query) Filter to return only artworks that have a web image asset 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func everythingGet(page: Int, itemsPerPage: Int, hasImages: Int, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [Artwork]?, _ error: Error?) -> Void)) -> RequestTask {
        return everythingGetWithRequestBuilder(page: page, itemsPerPage: itemsPerPage, hasImages: hasImages).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Artworks List
     - GET /collection
     - parameter page: (query) Number of page 
     - parameter itemsPerPage: (query) Limit of artworks by page 
     - parameter hasImages: (query) Filter to return only artworks that have a web image asset 
     - returns: RequestBuilder<[Artwork]> 
     */
    open class func everythingGetWithRequestBuilder(page: Int, itemsPerPage: Int, hasImages: Int) -> RequestBuilder<[Artwork]> {
        let localVariablePath = "/collection"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page.encodeToJSON(), isExplode: true),
            "items_per_page": (wrappedValue: itemsPerPage.encodeToJSON(), isExplode: true),
            "has_images": (wrappedValue: hasImages.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Artwork]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
