//
// Artwork.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Artwork: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var title: String?
    public var images: [String]?
    public var description: String?
    public var dating: String?
    public var medium: [String]?
    public var primaryMaker: String?

    public init(id: String? = nil, title: String? = nil, images: [String]? = nil, description: String? = nil, dating: String? = nil, medium: [String]? = nil, primaryMaker: String? = nil) {
        self.id = id
        self.title = title
        self.images = images
        self.description = description
        self.dating = dating
        self.medium = medium
        self.primaryMaker = primaryMaker
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case images
        case description
        case dating
        case medium
        case primaryMaker
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(dating, forKey: .dating)
        try container.encodeIfPresent(medium, forKey: .medium)
        try container.encodeIfPresent(primaryMaker, forKey: .primaryMaker)
    }
}

